services:
    davidiq.topictitlecolor.listener:
        class: davidiq\topictitlecolor\event\main_listener
        arguments:
            - '@user'
            - '@dbal.conn'
            - '@template'
            - '@request'
            - '@auth'
            - '%core.table_prefix%'
        tags:
            - { name: event.listener }
